name: CI/CD pipe line
on: [push]
jobs:
  read_the_files: 
   runs-on: self-hosted
   steps:
    - name: sudo apt update
      run: sudo apt update
    - name : git clone 
      uses: actions/checkout@v2
    - name: check directory
      run: pwd  
    # - name: cd git-hub-action
    #   run: cd git-hub-action && ls -a && cat royal.tx
    - name: cat royal.tx
      run: cat royal.tx