name: CI/CD pipe line
on: [push]
jobs:
  read_the_files: 
   runs-on: self-hosted
   steps:
    - name: sudo apt update
      run: sudo apt update
    - name: intall nginx
      run: sudo apt install nginx -y
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: check directory
      run: pwd