name: CI/CD pipe line
on: [push]
jobs:
  read_the_files: 
   runs-on: ubuntu-latest
   steps:
    - name: sudo apt update
      run: sudo apt update
    - name: sudo apt install git
      run: sudo apt install git