name: CI/CD pipe line
on: [push]
jobs:
  read_the_files: 
   runs-on: ubuntu-latest
   steps:
    - name: sudo apt update
      run: sudo apt update
    - name: sudo apt install git
      run: sudo apt install git
    - name: git clone
      run: git clone https://github.com/royal231288/git-hub-action.git
    - name: ls -a
      run: ls -a